import Head from 'next/head'
import {NextPage} from "next";

import Header from "@/components/Header";
import Banner from '@/components/Banner';

const Home: NextPage = () => {
    return (
        <div className='relative h-screen bg-gradient-to-b from-gray-900/10 to-[#010511] lg:h-[140vh]'>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <main>
                <Banner/>
            </main>
        </div>
    )
};

export default Home;
