import Head from 'next/head'
import {NextPage} from "next";
import Header from "@/components/Header";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <main>

            </main>
        </>
    )
};

export default Home;
